namespace ChinookApp.Models
{
    /// <summary>
    /// Represents a customer in the Chinook database. This class:
    /// 1. Defines properties for all customer attributes.
    /// 2. Matches the structure of the Customer table in the database.
    /// 3. Provides a data model for customer-related operations.
    /// </summary>
    public class Customer
    {
        /// <summary>
        /// Gets or sets the unique identifier for the customer.
        /// This is typically auto-generated by the database.
        /// </summary>
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets the first name of the customer.
        /// This field is required and cannot be null.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the last name of the customer.
        /// This field is required and cannot be null.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the company name of the customer.
        /// This field is optional and can be null.
        /// </summary>
        public string Company { get; set; }

        /// <summary>
        /// Gets or sets the address of the customer.
        /// This field is optional and can be null.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets the city where the customer resides.
        /// This field is optional and can be null.
        /// </summary>
        public string City { get; set; }

        /// <summary>
        /// Gets or sets the state where the customer resides.
        /// This field is optional and can be null.
        /// </summary>
        public string State { get; set; }

        /// <summary>
        /// Gets or sets the country where the customer resides.
        /// This field is optional and can be null.
        /// </summary>
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets the postal code of the customer's address.
        /// This field is optional and can be null.
        /// </summary>
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or sets the phone number of the customer.
        /// This field is optional and can be null.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets the fax number of the customer.
        /// This field is optional and can be null.
        /// </summary>
        public string Fax { get; set; }

        /// <summary>
        /// Gets or sets the email address of the customer.
        /// This field is required and cannot be null.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the ID of the support representative assigned to the customer.
        /// This field is optional and can be null, represented as a nullable int.
        /// </summary>
        public int? SupportRepId { get; set; }
    }

    /// <summary>
    /// Represents the count of customers in a specific country.
    /// This class is used for reporting purposes, specifically for the 
    /// "Customer Count by Country" feature.
    /// </summary>
    public class CustomerCountry
    {
        /// <summary>
        /// Gets or sets the name of the country.
        /// This field cannot be null and represents a unique country name.
        /// </summary>
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets the number of customers in the country.
        /// This field represents the count of customers associated with the country.
        /// </summary>
        public int CustomerCount { get; set; }
    }

    /// <summary>
    /// Represents a customer's spending information.
    /// This class is used for reporting purposes, specifically for the
    /// "Top Spenders" feature.
    /// </summary>
    public class CustomerSpender
    {
        /// <summary>
        /// Gets or sets the unique identifier of the customer.
        /// This corresponds to the CustomerId in the Customer table.
        /// </summary>
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets the full name of the customer.
        /// This is typically a concatenation of FirstName and LastName.
        /// </summary>
        public string CustomerName { get; set; }

        /// <summary>
        /// Gets or sets the total amount spent by the customer.
        /// This represents the sum of all invoice totals for the customer.
        /// </summary>
        public decimal TotalSpent { get; set; }
    }

    /// <summary>
    /// Represents a customer's favorite music genre.
    /// This class is used for reporting purposes, specifically for the
    /// "Most Popular Genre for Customer" feature.
    /// </summary>
    public class CustomerGenre
    {
        /// <summary>
        /// Gets or sets the unique identifier of the customer.
        /// This corresponds to the CustomerId in the Customer table.
        /// </summary>
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets the full name of the customer.
        /// This is typically a concatenation of FirstName and LastName.
        /// </summary>
        public string CustomerName { get; set; }

        /// <summary>
        /// Gets or sets the name of the customer's favorite music genre.
        /// This represents the genre with the most purchases for this customer.
        /// </summary>
        public string GenreName { get; set; }

        /// <summary>
        /// Gets or sets the number of purchases the customer has made in this genre.
        /// This count helps determine which genre is the most popular for the customer.
        /// </summary>
        public int PurchaseCount { get; set; }
    }
}